version: 2
jobs:
  build:
    docker:
      - image: rgielen/selenium-firefox-maven
    working_directory: ~/repo
    environment:
      MAVEN_OPTS: -Xmx3200m
    steps:
      - checkout
      - run: mvn dependency:go-offline
      - run: mvn integration-test
