version: 2
jobs:
  build:
    docker:
      - image: rgielen/selenium-firefox-maven
    working_directory: ~/repo
    environment:
      MAVEN_OPTS: -Xmx3200m
    steps:
      - checkout
      - dependencies:
          post:
            - mkdir drivers
            - wget https://github.com/mozilla/geckodriver/releases/download/v0.11.1/geckodriver-v0.11.1-linux64.tar.gz && tar -zxvf geckodriver-v0.11.1-linux64.tar.gz:
                pwd: drivers
      - run: mvn dependency:go-offline
      - run: mvn integration-test
