version: 2.1
        jobs:
           build:
            working_directory: ~/repo
            docker:
              - image: circleci/openjdk:8-jdk
            steps:
              - checkout
              - run: mvn dependency:go-offline
              - run: mvn integration-test